/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cConverter;

/**
 *
 * @author rehena
 */
public class Converter extends javax.swing.JFrame {

    
    double USA_Dolar = 0.0125;
    double UK_POUND = 0.134;
    double India_Rupe = 0.4;
    double UAE_Dinar = 0.046;
    double Nepal_Rupee =1.27;
    double Bhutan_Ngultrum = 0.80;
    double SaudiArab_Riyal = 0.047;
    double Pkistan_Rupee = 1.30;
    double Singapore_dolar = 0.017;
    
    
    public Converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboCurrency = new javax.swing.JComboBox<>();
        jLabelConvert = new javax.swing.JLabel();
        jTextFieldConvert = new javax.swing.JTextField();
        jButtonConvert = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Currency Converter ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 540, 90));

        jComboCurrency.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE ONE...", "BHUTAN", "INDIA", "PAKISTAN", "SINGAPORE", "NEPAL", "SAUDI ARAB", "USA", "UK", "UAE", " ", " ", " " }));
        jComboCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCurrencyActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 239, 222, 38));

        jLabelConvert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelConvert.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(jLabelConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 297, 341, 76));

        jTextFieldConvert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextFieldConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 169, 341, 64));

        jButtonConvert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonConvert.setForeground(new java.awt.Color(0, 204, 51));
        jButtonConvert.setText("CONVERT");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 419, -1, 64));

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(0, 0, 204));
        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 419, 163, 64));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 51, 51));
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 165, 62));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("   BANGLADESHI (TK)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, 290, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CONVERTED CURRENCY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 306, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cConverter/simple-backgrounds-8.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed

        
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
       
        jTextFieldConvert.setText(null);
        jLabelConvert.setText(null);
        jComboCurrency.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
       
        double Bangladesh_Taka = Double.parseDouble( jTextFieldConvert.getText());
            
        if( jComboCurrency.getSelectedItem().equals("USA")){
            
            String cConverter1 = String.format("$ %.2f",Bangladesh_Taka* USA_Dolar);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("UK")){
            
            String cConverter1 = String.format("P %.2f",Bangladesh_Taka* UK_POUND);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("UAE")){
            
            String cConverter1 = String.format("D %.2f",Bangladesh_Taka* UAE_Dinar);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("INDIA")){
            
            String cConverter1 = String.format("R   %.2f",Bangladesh_Taka*India_Rupe);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("NEPAL")){
            
            String cConverter1 = String.format("R   %.2f",Bangladesh_Taka*Nepal_Rupee);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("PAKISTAN")){
            
            String cConverter1 = String.format("R   %.2f",Bangladesh_Taka*Pkistan_Rupee);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("SINGAPORE")){
            
            String cConverter1 = String.format("$   %.2f",Bangladesh_Taka*Singapore_dolar);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("SAUDI ARAB")){
            
            String cConverter1 = String.format("R   %.2f",Bangladesh_Taka*SaudiArab_Riyal);
            jLabelConvert.setText(cConverter1);
            
        }
        if( jComboCurrency.getSelectedItem().equals("BHUTAN")){
            
            String cConverter1 = String.format("N  %.2f",Bangladesh_Taka*Bhutan_Ngultrum);
            jLabelConvert.setText(cConverter1);
            
        }
       
       
       
       
        
        
    }//GEN-LAST:event_jButtonConvertActionPerformed

    private void jComboCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCurrencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelConvert;
    private javax.swing.JTextField jTextFieldConvert;
    // End of variables declaration//GEN-END:variables
}
